version: '3.9'

services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    command: yarn start
    stdin_open: true
    tty: true
    volumes:
      - ./client/src:/usr/src/app/src


  api:
    command: yarn start
    volumes:
      - ./server/src:/usr/src/app/src
